"""
Executes a design of experiment trials distributed with joblib.
"""

import os
import pickle
from joblib import Parallel, delayed
from typing import Any, Optional, Union, Tuple

from raxpy.spaces.dimensions import convert_values_from_dict
from raxpy.does import doe


def _run_trial(f, arg_set, result_file_path=None):
    """Run one trial and optionally persist its result."""
    result = f(**arg_set)
    if result_file_path is not None:
        os.makedirs(os.path.dirname(result_file_path), exist_ok=True)
        with open(result_file_path, "wb") as result_file:
            pickle.dump(result, result_file)
    return result


def perform_experiment(
    experiment_design: doe.DesignOfExperiment,
    f,
    n_jobs: int,
    session_folder_path: Optional[str] = None,
    sub_folders: Union[int, Tuple[str, ...]] = 2,
):
    """
    Executes the experiment design, parallalizing the execution of
    trials with joblib.  The trials results are saved into the
    session folder, if provided, in sub-folders defined by the first
    n dimensions of the input space or by the specified dimension ids.
    If the session folder is provided, any trials that have already been
    completed will be skipped.

    Arguments
    ---------
    experiment_design: doe.DesignOfExperiment
        the design of experiment to execute
    f: callable
        the function to execute for each trial
    n_jobs: int
        the number of jobs to run in parallel
    session_folder_path: Optional[str]
        the path to the session folder, trails will be saved in sub-folders of this folder
    sub_folders: Union[int, Tuple[str, ...]]
        if an int, the number of sub-folder levels to create for each trial, using the first n dimensions of the input space to define the sub-folder names
        if a tuple of str, the ids of dimensions to use for the sub-folders to create for each trial

    Returns
    -------
        a list of outputs generated by f in the order specified
        in the experiment design
    """
    value_dicts = experiment_design.input_space.convert_flat_values_to_dict(
        experiment_design.decoded_input_sets, experiment_design.input_set_map
    )
    arg_sets = list(
        convert_values_from_dict(
            experiment_design.input_space.dimensions, value_dict
        )
        for value_dict in value_dicts
    )

    if isinstance(sub_folders, int):
        if sub_folders < 0:
            raise ValueError("sub_folders must be non-negative")
        path_dimensions = experiment_design.input_space.dimensions[
            :sub_folders
        ]
    else:
        dimensions_by_id = {
            dimension.id: dimension
            for dimension in experiment_design.input_space.dimensions
        }
        missing_dimensions = [
            dimension_id
            for dimension_id in sub_folders
            if dimension_id not in dimensions_by_id
        ]
        if missing_dimensions:
            raise ValueError(
                f"Unknown sub-folder dimensions: {missing_dimensions}"
            )
        path_dimensions = [
            dimensions_by_id[dimension_id] for dimension_id in sub_folders
        ]

    tasks = []
    outputs: list[Any] = [None] * len(arg_sets)
    for index, (arg_set, value_dict) in enumerate(zip(arg_sets, value_dicts)):
        result_file_path = None
        if session_folder_path is not None:
            path_parts = [
                f"{dimension.id}={value_dict.get(dimension.local_id, dimension.default_value)}"
                for dimension in path_dimensions
            ]
            trial_folder = os.path.join(session_folder_path, *path_parts)
            result_file_path = os.path.join(
                trial_folder, f"data_point_{index}.pkl"
            )
            if os.path.exists(result_file_path):
                with open(result_file_path, "rb") as result_file:
                    outputs[index] = pickle.load(result_file)
                continue  # ensure task is not appended if result already exists
        tasks.append((index, arg_set, result_file_path))

    with Parallel(n_jobs=n_jobs) as parallel_pool:
        completed = parallel_pool(
            delayed(_run_trial)(f, arg_set, result_file_path)
            for _, arg_set, result_file_path in tasks
        )

    for (index, _, _), result in zip(tasks, completed):
        outputs[index] = result

    return arg_sets, outputs
